factor in attempt

diff --git a/rsa b/rsa
--- a/rsa
+++ b/rsa
@@ -29,6 +29,13 @@ check_factor()
 			num2=$numcp
 		fi
 
+	for factor in $(factor $num1); do
+		if [ $factor -ne 1 ]; then
+			echo "Error: $factor is not a prime number."
+			exit 1
+		fi
+	done
+
 	echo "$num$num1*$num2"
 }
 
